language: python
python: 3.7
cache: 'pip'
services:
- docker

jobs:
  include:
  - name: "lint"
    before_script:
    - sudo apt-get -qq update
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - poetry config virtualenvs.create false
    - poetry install
    script:
    - poetry run scripts/lint
    - poetry run pytest
    if: type = "pull_request"
